### ISSUE TITLE
Not finishing with a / on a directory leads to all sorts of funkiness

### ISSUE THREAD

**Issue by KyGost** [RangerMauve/dat-fetch#11]
See RangerMauve/agregore-browser#36

**Comment by KyGost** [comment]
Will come back to this some other time.
Can't fix `/client` vs `/client/` issue.
The renaming won't occur as RangerMauve/agregore-browser doesn't check finalPath (nor do other implementations I'd expect).
The only issue my fix fixes is the index following the name of the used path.

**Comment by KyGost** [comment]
Stat.isDirectory isn't the issue.
Magic to me as to how it works but looks like it is doing something to do with filetypes via a bitmask?
https://github.com/hypercore-protocol/hyperdrive-schemas/blob/master/lib/stat.js#L86

**Comment by KyGost** [comment]
My best guess is it has to do with a rogue hyperdrive block.
Not sure how to investigate that. Will get around to it eventually I'm sure.
(or keep procastinating sleep and do it now)

**Comment by RangerMauve** [comment]
Oh! I was thinking one way to do it would be something like this:

- in the `stat.isDirectory()` block
- Detect whether the url ends with a `/`
- If it doesn't, immediately return a FakeResponse with a redirect using status code 301 and appending the `/` to the URL

With the 301 status code, the browser should detect the new URL and load it from there

**Comment by KyGost** [comment]
Oh awesome! Didn't know about that. Thanks, will try.

**Comment by KyGost** [comment]
I won't bother submitting a PR-- here's the change so far:
https://github.com/RangerMauve/dat-fetch/blob/master/index.js#L183
```diff
if (stat.isDirectory()) {
+         if (!path.endsWith('/')) {
+           responseHeaders.set('Location', path + '/')
+           return new FakeResponse(301, 'Bad URL', responseHeaders, intoStream(''), url + '/');
+         }
          const stats = await archive.readdir(finalPath, { includeStats: true })
          const files = stats.map(({ stat, name }) => (stat.isDirectory() ? `${name}/` : name))
```

**Comment by KyGost** [comment]
Closing for now
