### ISSUE TITLE
CREATE method

### ISSUE THREAD

**Issue by KyGost** [RangerMauve/dat-fetch#17]
I think there should be a `CREATE` method.

An option would be something like creating a drive with name Kopple + (current system time) but this is kinda yuck.

Currently because of CORS stuff, getting the address isn't be possible. This is a different issue though.

What about a new method, not sure how it would work with the URL, perhaps ignore the contents?
Example:
```js
fetch('hyper://new', {method: 'CREATE'}) (returns address)
```

Beaker uses `beaker.hyperdrive.createDrive` which returns a drive object which contains the URL of the created drive.

**Comment by RangerMauve** [comment]
What's the purpose of having a dedicated create method compared to the auto-creation that's already there based on drive names?

**Comment by KyGost** [comment]
As mentioned, one can get around it by using something like system time and assuming that no one will have tried to use that name yet but it's kinda yuck. It'd just be nicer to have it be a dedicated thing that creates a non-named drive. (IMO)

**Comment by RangerMauve** [comment]
Hmm, I guess I an unwritten guideline I had for naming schemes was to use application names like

`hyper://fritter-profile` so if another application wanted to use your fritter profile it could get access to it that way too.

**Comment by RangerMauve** [comment]
Could you maybe elaborate how you'd imagine using CREATE vs using the naming function in an application?

**Comment by KyGost** [comment]
Hmm.. Just using names makes sense I guess.
Just trying to think of reasons against that, perhaps being able to sandbox the drive.
Perhaps this isn't enough of a reason though.

What about having multiple? Check if drive exists yet, if not use that, if yes, append something (and repeat)?

**Comment by RangerMauve** [comment]
For multiple drives I was imagining you'd either track the names inside localstorage, or mount them on the main application drive or something of the sort.

**Comment by KyGost** [comment]
That makes sense.

What about a malicious site eating the drives of other sites?
Ie. `BigPhotoEditor` always takes the drive `hyper://BigPhotoEditorPhotos` as per its code.
`MaliciousSite` uses `hyper://BigPhotoEditorPhotos` before the user creates the drive.

Is there anything malicious that the site can do?
I mean I guess the malicious site could inflate the drive? That's not a big problem though.
Maybe we just need to keep it in mind for future CORS stuff?

Can you think of any issues? If not I guess we don't need `CREATE`

**Comment by RangerMauve** [comment]
As per our discord discussion:

- Maybe we should error when a site gets accessed before it's first PUT
- and have an extension exist which prompts the user to accept the initial PUT request for a given origin
- That way rogue sites can't pollute a site's index.json without the user allowing it first
- Also sites cant create drives without user consent (important for tracking)
- You can keep a drive private if you put a CORS header int he index.json that limits access from other domains
